Django/Lab2/bookstore/books/urls.py
from django.urls import path
from .views import books_index, book_details, book_delete, book_update, book_create

app_name = 'books'


urlpatterns = [
    path('index', books_index, name='book-index'),
    path('details/<int:pk>', book_details, name="book-detail"),
    path('delete/<int:pk>', book_delete, name="book-delete"),
    path('update/<int:pk>', book_update, name="book-update"),
    path('create/', book_create, name="book-create"),
]

Django/Lab2/bookstore/books/models.py
from django.db import models

# Create your models here.

class book(models.Model):
        title = models.CharField("Book Title", max_length=3, unique=True)
        description = models.TextField("Book Description")
        rate = models.PositiveIntegerField(default=0)
        views = models.PositiveIntegerField(default=0)
        created_at = models.DateTimeField(auto_now_add=True)
        updated_at = models.DateTimeField(auto_now=True)
        
        def __str__(self):
            return f"Title {self.title}"

Django/Lab2/bookstore/books/forms.py
from django.forms import ModelForm
from .models import book


class bookForm(ModelForm):
    class Meta:
        model = book
        # fields = '__all__'
        fields = ['title', 'description', 'rate', 'views']

Django/Lab2/bookstore/books/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from .models import book
from django.views.decorators.csrf import csrf_exempt
from .forms import bookForm

def books_index(request):
    books = book.objects.all()
    return render(request, 'book/book_index.html', context={"books": books})
    
def book_details(request, pk):
    singlebook = book.objects.get(pk=pk)
    return render(request, 'book/book_details.html', context={"book": singlebook})

def book_delete(request, pk):
    book.objects.get(pk=pk).delete()
    return redirect("books:book-index")

def book_create(request):
    form = bookForm()
    if request.method == "POST":
        form = bookForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("books:book-index")
    return render(request, 'book/book_create.html', context={
        'form': form
    })

def book_update(request, pk):
    singlebook = book.objects.get(pk=pk)
    form = bookForm(instance=singlebook)
    if request.method == "POST":
        form = bookForm(data=request.POST, instance=singlebook)
        if form.is_valid():
            form.save()
            return redirect("books:book-index")
    print("moshkela")    
    return render(request, 'book/book_update.html', context={
        'form': form, 
        'book': singlebook
    }) 

Django/Lab2/bookstore/books/templates/book/book_create.html
{% extends 'main/base_layout.html' %}
{% block main-content %}
<div class="container">
    <div class="row">
        <div class="text-center col-12">

            <form method="post" action="{% url 'books:book-create' %}" enctype="multipart/form-data">
            {% csrf_token %}
                {{ form.as_p }}

                {% comment %}
                <div class="form-group">
                    <label for="bookName">Title</label>
                    <input type="text" name="name" class="form-control" id="bookName" placeholder="Enter name">
                </div>

                <div class="form-group">
                    <label for="bookDesc"> Description</label>
                    <input type="text" name="desc" class="form-control" id="bookDesc" placeholder="Enter Description">
                </div>

                <div class="form-group">
                    <label for="bookLikes"> Rate</label>
                    <input type="number" name="likes" class="form-control"
                           placeholder="Enter Rate">
                </div>

                <div class="form-group">
                    <label for="bookLikes"> Views</label>
                    <input type="number" name="likes" class="form-control""
                           placeholder="Enter Rate">
                </div>
                {% endcomment %}





                <button type="submit" class="btn btn-primary">Submit</button>
                <div class="text-center mt-5" style="display:inline">
                    <a href="{% url 'books:book-index'%}">
                        <button type="button" class="btn btn-info">
                            Back to books Index
                        </button>
                    </a>
                </div>
            </form>
        </div>


    </div>
</div>
{% endblock %}

Django/Lab2/bookstore/books/templates/book/book_details.html
{% extends 'main/base_layout.html' %}
{% block main-content %}
<div class="container">
    <div class="row">
        <div class="text-center col-12">
            <div class="card">
                <div class="card-title">
                    {{book.title}}
                </div>
                <div>{{book.description}}</div>
                <div>{{book.rate}}</div>
                <div>{{book.views}}</div>

            </div>


        </div>


    </div>
</div>
{% endblock %}

Django/Lab2/bookstore/books/templates/book/book_index.html
{% extends 'main/base_layout.html' %}

{% block main-content %}


<table class="table">
    <thead>
    <tr>
        <td>Title</td>
        <td>Description</td>
        <td>Rate</td>
        <td>Views</td>
        <td>Actions</td>
    </tr>
    </thead>

    <tbody>
    {% for book in books %}

    <tr>
        <td>{{book.title}}</td>
        <td>{{book.description}}</td>
        <td>{{book.rate}}</td>
        <td>{{book.views}}</td>
        <td>
            <a href="{% url 'books:book-detail' book.id %}" class="btn btn-info"> View</a>
            <a href="{% url 'books:book-update' book.id %}" class="btn btn-warning"> Update</a>
            <a href="{% url 'books:book-delete' book.id %}" class="btn btn-danger"> Delete</a>

        </td>
    </tr>
    {% endfor %}

    </tbody>
</table>

{% endblock %}

Django/Lab2/bookstore/books/templates/book/book_update.html
{% extends 'main/base_layout.html' %}
{% block main-content %}
<div class="container">
    <div class="row">
        <div class="text-center col-12">

            <form method="post" action="{% url 'books:book-update' book.id %}" enctype="multipart/form-data">
            {% csrf_token %}
                {{ form.as_p }}

                {% comment %}
                <div class="form-group">
                    <label for="bookName">Title</label>
                    <input type="text" name="name" class="form-control" placeholder="Enter name">
                </div>

                <div class="form-group">
                    <label for="bookDesc"> Description</label>
                    <input type="text" name="desc" class="form-control" placeholder="Enter Description">
                </div>

                <div class="form-group">
                    <label for="bookLikes"> Rate</label>
                    <input type="number" name="likes" class="form-control"
                           placeholder="Enter Rate">
                </div>

                <div class="form-group">
                    <label for="bookLikes"> Views</label>
                    <input type="number" name="likes" class="form-control""
                           placeholder="Enter Rate">
                </div>
                {% endcomment %}





                <button type="submit" class="btn btn-primary">Update</button>
                <div class="text-center mt-5" style="display:inline">
                    <a href="{% url 'books:book-index'%}">
                        <button type="button" class="btn btn-info">
                            Back to books Index
                        </button>
                    </a>
                </div>
            </form>
        </div>


    </div>
</div>
{% endblock %}