Django/Lab1/Lab1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('bookstore/', include('bookstore.urls')),
]

Django/Lab1/bookstore/urls.py
from django.urls import path
from .views import index, bookstore_list, bookstore_detail, bookstore_delete, bookstore_update

app_name = 'bookstore'


urlpatterns = [
    path('index', index, name='bookstore-index'),
    path('bookstore_list/', bookstore_list, name="bookstore-list"),
    path('bookstore_detail/<int:book_id>', bookstore_detail, name="bookstore-detail"),
    path('bookstore_delete/<int:book_id>', bookstore_delete, name="bookstore-delete"),
    path('bookstore_update/<int:book_id>', bookstore_update, name="bookstore-update")
]

Django/Lab1/home/urls.py
from django.urls import path
from .views import index


urlpatterns = [
    path('', index, name='home-index')
]

Django/Lab1/bookstore/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect

# Create your views here.
def index(request):
    return render(request, 'main/base_layout.html')


book_list = [
    {
        'index': 0,
        'id': 1,
        'Title': '50 Laws of power',
        'Author': 'Robert Greene',
        'Genre': "Human",
    },
    {
        'index': 1,
        'id': 2,
        'Title': 'Harry Potter',
        'Author':'J.K Rowling',
        'Genre': "Fiction",
    },
    {
        'index': 2,
        'id': 3,
        'Title': 'Song Of Ice and fire',
        'Author': 'George Martin',
        'Genre': "Action ",
    },
]


def _get_book(book_id):
    for book in book_list:
        if 'id' in book and book['id'] == book_id:
            return book
    return None
    
def bookstore_list(request):
    my_context = {'book_list': book_list}
    # template_loader > todo/templates/
    return render(request, 'bookstore/books_list.html', context=my_context)

def bookstore_detail(request, *args, **kwrgs):
    book_id = kwrgs.get('book_id')
    book_object = _get_book(book_id)
    my_context = {
        'book_id': book_object.get('id'),
        'book_title': book_object.get('Title'),
        'book_author': book_object.get('Author'),
        'book_genre': book_object.get('Genre')
    }

    return render(request, 'bookstore/book_details.html', context=my_context)


def bookstore_delete(request, **kwargs):
    book_id = kwargs.get('book_id')
    book_object = _get_book(book_id)
    if book_list:
        book_list.remove(book_object)
    return redirect('bookstore:bookstore-list')   

def bookstore_update(request, **kwargs):
    book_id = kwargs.get('book_id')
    book_object = _get_book(book_id)
    for book in book_list:
        if book == book_object:
            book['Author'] = f"Update {book_object['Author']}"
            
    return redirect('bookstore:bookstore-list') 

Django/Lab1/home/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    # return plain text
    return HttpResponse("Hello OS")

Django/Lab1/bookstore/templates/bookstore/book_details.html
{% extends 'main/base_layout.html' %}


{% block main-content %}
 <h1> Welcome to book details </h1>
 <table class="table">
    <thead>
        <tr>
            <td> ID </td>
            <td> Title </td>
            <td> Author </td>
            <td> Genre </td>
        </tr>
    </thead>
    <tbody>

        <tr {% if book_priority > 3 %} style="color:red" {% else %} style="color:green" {% endif %} >
            <td>{{ book_id }} </td>
            <td>{{ book_title }} </td>
            <td> {{ book_author }}</td>
            <td> {{ book_genre}} </td>
        </tr>
    </tbody>

 </table>

{% endblock %}


<a href="{% url 'bookstore:index' %}"> Back to Index</a>
<a href="{% url 'book:books-list' %}"> Back to List</a>

Django/Lab1/bookstore/templates/bookstore/books_list.html
{% extends 'main/base_layout.html' %} {# override block title #} {% block title %} Book Store book list {% endblock %} {# override body #} {% block main-content%}
<table class="table table-condensed">
  <thead>
    <tr>
      <td>ID</td>
      <td>Name</td>
      <td>Title</td>
      <td>Genre</td>
      <td>Actions</td>
    </tr>
  </thead>

  <tbody>
    {% for book in book_list%}
    <tr>
      <td>{{ book.id }}</td>
      <td>{{ book.Title }}</td>
      <td>{{ book.Author }}</td>
      <td>{{ book.Genre}}</td>

      <td>
        <a
          class="btn btn-info"
          href="{% url 'bookstore:bookstore-detail' book.id %}"
        >
          View</a
        >
        <a
          class="btn btn-info"
          href="{% url 'bookstore:bookstore-update' book.id %}"
        >
          Update</a
        >
        <a
          class="btn btn-danger"
          href="{% url 'bookstore:bookstore-delete' book.id %}"
        >
          Delete</a
        >
      </td>
    </tr>

    {% empty %}
    <tr>
      <td colspan="3" class="text-center">sorry, no books in the list</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}